name: "Broken Link Checker"

on: push

jobs:
    link_check:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: git action
          uses: actions/checkout@master
          with:
            fetch-depth: 0
        - name: Broken Link Script
          run: |
            chmod +x ./.github/workflow_scripts/link_check.sh && ./.github/workflow_scripts/link_check.sh
        
        - name: Commit & Push changes
          uses: actions-js/push@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Check CSV Files
          shell: python
          run: |
            import pandas as pd
            df = pd.read_csv("Broken Links Stable.csv") 
            if not df.empty: 
                exit(1)
            df = pd.read_csv("Broken Links Dev.csv") 
            if not df.empty: 
                exit(1)
